name: Forms Check
on:
  schedule: [{cron: "0 7 * * *"}]
  workflow_dispatch:
jobs:
  forms:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl --fail https://lavieenrosecafe.in/locations.html
          curl --fail https://lavieenrosecafe.in/franchise.html
