name: Security Check
on:
  schedule: [{cron: "30 6 * * 1"}]
  workflow_dispatch:
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -I https://lavieenrosecafe.in
          curl --fail https://lavieenrosecafe.in/robots.txt
          curl --fail https://lavieenrosecafe.in/sitemap.xml
