name: Forms Check

on:
  schedule:
    - cron: "30 7 * * *"
  workflow_dispatch:

jobs:
  forms:
    runs-on: ubuntu-latest

    steps:
      - name: Check Locations Page
        run: |
          curl --fail --silent --show-error https://lavieenrosecafe.in/locations.html

      - name: Check Franchise Page
        run: |
          curl --fail --silent --show-error https://lavieenrosecafe.in/franchise.html
