name: Website Uptime

on:
  schedule:
    - cron: "15 * * * *"
  workflow_dispatch:

jobs:
  uptime:
    runs-on: ubuntu-latest

    steps:
      - name: Check Website
        run: |
          curl --fail --silent --show-error https://lavieenrosecafe.in

      - name: Check Booking Page
        run: |
          curl --fail --silent --show-error https://lavieenrosecafe.in/booking

      - name: Check Franchise Page
        run: |
          curl --fail --silent --show-error https://lavieenrosecafe.in/franchise
